import type {Locale} from './routing';
import type {VideoCategory} from '@/lib/beginner-videos';

type VideoMessages = {title: string; intro: string; all: string; watch: string; browse: string; english: string; recommended: string; filter: string; count: string; homeTitle: string; search: string; searchPlaceholder: string; hideClasses: string; chapters: string; empty: string; reset: string; categories: Record<VideoCategory, string>};
export const videoMessages: Record<Locale, VideoMessages> = {
  en: {title: 'Beginner video guides', intro: 'Find a walkthrough for controls, leveling, equipment, crafting or your class. Chapter links take you straight to the relevant demonstration on YouTube.', all: 'All videos', watch: 'Watch on YouTube', browse: 'Browse all video guides', english: 'English audio', recommended: 'Watch the steps', filter: 'Filter videos by topic', count: 'videos', homeTitle: 'Six videos to get started', search: 'Search videos', searchPlaceholder: 'Topic, class or creator', hideClasses: 'Hide class supplements', chapters: 'Jump to a chapter', empty: 'No videos match these filters.', reset: 'Clear filters', categories: {basics: 'Beginner systems', 'first-day': 'First day', settings: 'Settings & controls', leveling: 'Leveling', 'level-45': 'After level 45', gear: 'Equipment', crafting: 'Crafting', 'week-one': 'Daily & weekly', mistakes: 'Mistakes to avoid', class: 'Class supplements'}},
  ja: {title: '初心者向け動画ガイド', intro: '操作設定、レベル上げ、装備、製作、職業別の実演を探せます。チャプターリンクからYouTubeの該当場面に移動できます。', all: 'すべての動画', watch: 'YouTubeで見る', browse: 'すべての動画ガイド', english: '英語音声', recommended: '操作を動画で確認', filter: 'テーマで動画を絞り込む', count: '件の動画', homeTitle: '最初に見る6本の動画', search: '動画を検索', searchPlaceholder: 'テーマ・職業・投稿者', hideClasses: '職業別の補足動画を隠す', chapters: 'チャプターに移動', empty: '条件に合う動画がありません。', reset: '絞り込みを解除', categories: {basics: '基本システム', 'first-day': '初日の進め方', settings: '設定と操作', leveling: 'レベル上げ', 'level-45': 'レベル45以降', gear: '装備', crafting: '製作', 'week-one': '日課と週課', mistakes: '避けたい失敗', class: '職業別の補足'}},
  es: {title: 'Vídeos para principiantes', intro: 'Encuentra demostraciones de controles, subida de nivel, equipo, fabricación y clases. Los capítulos abren directamente la sección correspondiente en YouTube.', all: 'Todos los vídeos', watch: 'Ver en YouTube', browse: 'Ver todas las guías en vídeo', english: 'Audio en inglés', recommended: 'Mira los pasos', filter: 'Filtrar vídeos por tema', count: 'vídeos', homeTitle: 'Seis vídeos para empezar', search: 'Buscar vídeos', searchPlaceholder: 'Tema, clase o creador', hideClasses: 'Ocultar vídeos de clases', chapters: 'Ir a un capítulo', empty: 'Ningún vídeo coincide con los filtros.', reset: 'Borrar filtros', categories: {basics: 'Sistemas básicos', 'first-day': 'Primer día', settings: 'Ajustes y controles', leveling: 'Subida de nivel', 'level-45': 'Después del nivel 45', gear: 'Equipo', crafting: 'Fabricación', 'week-one': 'Rutina diaria y semanal', mistakes: 'Errores que evitar', class: 'Guías de clases'}},
  de: {title: 'Videoguides für Einsteiger', intro: 'Finde Anleitungen zu Steuerung, Leveln, Ausrüstung, Herstellung und Klassen. Kapitellinks öffnen direkt die passende Vorführung auf YouTube.', all: 'Alle Videos', watch: 'Auf YouTube ansehen', browse: 'Alle Videoguides ansehen', english: 'Englische Vertonung', recommended: 'Die Schritte im Video ansehen', filter: 'Videos nach Thema filtern', count: 'Videos', homeTitle: 'Sechs Videos für den Einstieg', search: 'Videos suchen', searchPlaceholder: 'Thema, Klasse oder Ersteller', hideClasses: 'Klassenergänzungen ausblenden', chapters: 'Zum Kapitel springen', empty: 'Keine Videos passen zu diesen Filtern.', reset: 'Filter zurücksetzen', categories: {basics: 'Grundsysteme', 'first-day': 'Erster Tag', settings: 'Einstellungen & Steuerung', leveling: 'Leveln', 'level-45': 'Nach Stufe 45', gear: 'Ausrüstung', crafting: 'Herstellung', 'week-one': 'Tägliche & wöchentliche Aufgaben', mistakes: 'Fehler vermeiden', class: 'Klassenergänzungen'}},
};
