import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
catalogue = json.loads((ROOT / 'src/content/class-skills.json').read_text(encoding='utf-8'))
rows = {}

def add(class_id, entries):
    active = [s for s in catalogue[class_id] if s['kind'] == 'active']
    assert len(entries) == len(active) == 12
    rows[class_id] = [dict(id=s['id'], text=dict(zip(['en', 'ja', 'es', 'de'], entry))) for s, entry in zip(active, entries)]

add('gladiator', [
('Keen Strike restores MP and builds threat. Its rank-12 cooldown option feeds Ruinous Blow.', 'MPを回復し、敵対値を増やします。ランク12の特化でRuinous Blowの再使用を早めます。', 'Recupera MP y genera amenaza. La opción de rango 12 reduce la recarga de Ruinous Blow.', 'Stellt MP her und erzeugt Bedrohung. Die Option auf Rang 12 verkürzt die Abklingzeit von Ruinous Blow.'),
('Rending Blow hits nearby enemies. Choose reduced MP cost for sustain or the mobility option for movement.', '近くの敵を攻撃します。継戦にはMP消費軽減、移動が必要なら移動可能化を選びます。', 'Golpea enemigos cercanos. Elige menos coste de MP para sostener ataques o movilidad para desplazarte.', 'Trifft nahe Gegner. Wähle geringere MP-Kosten für längere Kämpfe oder die Bewegungsoption.'),
('Leaping Slam closes distance. Its on-kill reset is useful between small-enemy pulls.', '距離を詰めます。敵を倒した際の再使用リセットは連続した雑魚狩りに役立ちます。', 'Cierra distancia. Su reinicio al derrotar enemigos sirve para encadenar grupos pequeños.', 'Überbrückt Distanz. Der Rücksetzeffekt nach einem Kill hilft bei aufeinanderfolgenden kleinen Gegnergruppen.'),
('Mocking Blade knocks down vulnerable enemies and opens knockdown follow-ups.', '転倒が有効な敵を倒し、転倒を条件とする追撃につなげます。', 'Derriba a enemigos vulnerables y habilita ataques que requieren derribo.', 'Wirft anfällige Gegner zu Boden und eröffnet Folgeangriffe mit dieser Voraussetzung.'),
('Overhead Slam requires Knockdown, or a proc against control-immune targets. Use it when the opportunity appears.', '転倒、または行動不能免疫の敵への発動が条件です。使用可能になったら追撃します。', 'Requiere derribo o una activación contra enemigos inmunes al control. Úsalo cuando esté disponible.', 'Benötigt Niederschlag oder eine Auslösung gegen kontrollimmune Ziele. Nutze das tatsächliche Zeitfenster.'),
('Sword Aura Rampage requires Stagger. Save it for the stagger window; its movement and resource options change usability.', 'スタガー中の敵に使います。移動や資源回復の特化で、その時間帯の使い勝手が変わります。', 'Requiere tambaleo. Resérvalo para esa ventana; las opciones de movimiento y recursos cambian su uso.', 'Benötigt Taumeln. Hebe es für dieses Fenster auf; Bewegungs- und Ressourcenoptionen ändern die Nutzbarkeit.'),
('Ankle Slice opens after Parry, or after Leaping Slam with its trigger option. It roots enemies; a specialization adds knockdown.', 'パリィ後、または発動特化を選んだLeaping Slam後に使用できます。束縛を付与し、特化で転倒も狙えます。', 'Se abre tras parar o mediante la opción de activación de Leaping Slam. Inmoviliza; una especialización añade derribo.', 'Öffnet nach Parieren oder mit der Auslöseoption von Leaping Slam. Hält fest; eine Spezialisierung ergänzt Niederschlag.'),
('Crushing Wave attacks around you. Choose HP absorption for recovery; its critical reset requires the selected option.', '周囲を攻撃します。回復にはHP吸収を選択。クリティカルでのリセットには対応特化が必要です。', 'Ataca a tu alrededor. Usa absorción de HP para recuperarte; el reinicio por crítico requiere su opción.', 'Greift um dich herum an. HP-Absorption hilft bei Heilung; der kritische Reset benötigt die gewählte Option.'),
('Rush Strike approaches after Dodge or while flying. Keep it separate from attacks when movement is situational.', '回避後または飛行中に接近します。状況に応じた移動用に、反復攻撃とは分けて使います。', 'Se aproxima tras esquivar o al volar. Sepáralo de ataques repetidos cuando necesites controlar el movimiento.', 'Nähert sich nach Ausweichen oder im Flug. Halte es für situationsabhängige Bewegung getrennt.'),
('Aerial Snare follows Knockdown, with a proc against control-immune targets. Its immunity-damage option suits those targets.', '転倒後、または行動不能免疫の敵への発動時に使います。免疫対象へのダメージ特化を選べます。', 'Sigue a un derribo o se activa contra inmunes al control. La opción de daño contra inmunidad sirve para esos objetivos.', 'Folgt auf Niederschlag oder löst gegen kontrollimmune Ziele aus. Die Option gegen Immunität passt zu diesen Gegnern.'),
('Ruinous Blow approaches and grants Prepare for Battle. Use its damage buff before your main attack window.', '接近し、Prepare for Battleを付与します。主要な攻撃時間の前に強化を得ます。', 'Se aproxima y otorga Prepare for Battle. Activa su mejora antes de la ventana principal de daño.', 'Nähert sich und gewährt Prepare for Battle. Nutze den Schadensbuff vor deinem Hauptangriffsfenster.'),
('Defiance removes listed control effects and grants brief status immunity. Keep this escape on its own control.', '指定された行動阻害を解除し、短時間の状態異常免疫を得ます。解除用の独立した操作にします。', 'Elimina los controles indicados y otorga inmunidad breve. Mantén esta salida en un control independiente.', 'Entfernt die aufgeführten Kontrolleffekte und gewährt kurze Immunität. Halte diesen Ausweg separat erreichbar.'),
])

add('templar', [
('Vicious Strike restores MP and builds threat. Its rank-12 option reduces Warding Strike cooldown on hit.', 'MPを回復し、敵対値を増やします。ランク12の特化で命中時にWarding Strikeの再使用を短縮します。', 'Recupera MP y genera amenaza. Su opción de rango 12 reduce la recarga de Warding Strike al golpear.', 'Stellt MP her und erzeugt Bedrohung. Die Option auf Rang 12 verkürzt bei Treffern Warding Strike.'),
('Pummel builds threat. Select its Punishment cooldown reduction when building that damage loop.', '敵対値を増やします。Punishmentを軸にする場合は、その再使用短縮を選びます。', 'Genera amenaza. Selecciona la reducción de recarga de Punishment para ese ciclo de daño.', 'Erzeugt Bedrohung. Wähle die Verkürzung von Punishment für diesen Schadensablauf.'),
('Poach pulls a vulnerable target. Its immunity option moves you to an unpullable target; its kill reset helps farming.', '引き寄せ可能な敵を引きます。免疫対象へ自分が接近する特化や、撃破時リセットを選べます。', 'Atrae a un objetivo vulnerable. Una opción te acerca al inmune; el reinicio al matar facilita el farmeo.', 'Zieht ein anfälliges Ziel heran. Eine Option bewegt dich zu immunen Zielen; Kill-Resets helfen beim Farmen.'),
('Shield Smite opens Judgment for a short window. Its MP option removes the cost and restores MP on hit.', '短いJudgmentの使用時間を作ります。MP特化で消費をなくし、命中時にMPを回復します。', 'Habilita Judgment durante una ventana breve. La opción de MP elimina el coste y recupera MP al golpear.', 'Öffnet ein kurzes Fenster für Judgment. Die MP-Option entfernt Kosten und stellt bei Treffern MP her.'),
('Judgment is the follow-up to Shield Smite, Warding Strike, Shield Rush or Doom Shield. Use it before the trigger expires.', 'Shield Smite、Warding Strike、Shield Rush、Doom Shieldの追撃です。発動時間内に使います。', 'Es el seguimiento de Shield Smite, Warding Strike, Shield Rush o Doom Shield. Úsalo antes de vencer la activación.', 'Folgt auf Shield Smite, Warding Strike, Shield Rush oder Doom Shield. Nutze es vor Ablauf des Auslösefensters.'),
('Flash Rampage requires a staggered target. Spend the stagger window on this attack rather than waiting for normal control.', 'スタガー中の敵が条件です。通常の行動阻害を待たず、スタガーの時間に使います。', 'Requiere un objetivo tambaleándose. Aprovéchalo en esa ventana en vez de esperar un control normal.', 'Benötigt ein taumelndes Ziel. Nutze dieses Fenster, statt auf normale Kontrolle zu warten.'),
('Debilitating Smash opens after Block, or through Shield Smite’s trigger option. It reduces enemy defense.', 'ブロック後、またはShield Smiteの発動特化で使用でき、敵の防御を下げます。', 'Se abre tras bloquear o mediante la opción de activación de Shield Smite. Reduce defensa.', 'Öffnet nach Blocken oder durch Shield Smites Auslöseoption. Senkt die gegnerische Verteidigung.'),
('Warding Strike heals you, adds damage tolerance and opens Judgment. Vicious Strike can shorten its wait.', '自分を回復し、被ダメージ耐性を上げ、Judgmentを使えるようにします。Vicious Strikeで待ち時間を短縮できます。', 'Te cura, añade tolerancia al daño y habilita Judgment. Vicious Strike puede reducir la espera.', 'Heilt dich, erhöht Schadenstoleranz und öffnet Judgment. Vicious Strike kann die Wartezeit verkürzen.'),
('Shield Rush requires Dodge or flight, closes distance and opens Judgment. Avoid moving a boss away from your group.', '回避後または飛行中に接近し、Judgmentを開きます。ボスを味方から引き離さないよう使います。', 'Requiere esquivar o volar, cierra distancia y habilita Judgment. Evita alejar al jefe del grupo.', 'Benötigt Ausweichen oder Flug, überbrückt Distanz und öffnet Judgment. Ziehe den Boss dabei nicht von der Gruppe weg.'),
('Annihilate requires Stun or Knockdown, or a proc against control-immune targets. Choose its immunity-damage option for bosses.', 'スタン、転倒、または免疫対象への発動が条件です。ボスには免疫対象へのダメージ特化を検討します。', 'Requiere aturdimiento, derribo o activación contra inmunes. Usa su opción de daño contra inmunidad para jefes.', 'Benötigt Betäubung, Niederschlag oder eine Auslösung gegen immune Ziele. Wähle dafür die passende Schadensoption.'),
('Punishment is a charged area attack that grants Executor. Faster casting or mobile casting helps finish it safely.', 'チャージ範囲攻撃でExecutorを得ます。詠唱速度や移動可能化の特化で、安全に完了しやすくなります。', 'Es un ataque de área cargado que otorga Executor. La velocidad o movilidad de lanzamiento ayudan a terminarlo seguro.', 'Ist ein aufgeladener Flächenangriff mit Executor. Schnellere oder mobile Ausführung erleichtert einen sicheren Abschluss.'),
('Defiance removes listed control effects. It is a control break, not a substitute for blocking incoming damage.', '指定された行動阻害を解除します。解除用であり、攻撃をブロックする代わりにはなりません。', 'Elimina los controles indicados. Rompe control; no sustituye bloquear daño entrante.', 'Entfernt die aufgeführten Kontrolleffekte. Es löst Kontrolle und ersetzt keinen Block gegen Schaden.'),
])

add('assassin', [
('Quick Slice restores MP. Its rank-12 cooldown option helps you use Insignia Explosion more often.', 'MPを回復します。ランク12の特化でInsignia Explosionの使用回数を増やせます。', 'Recupera MP. Su opción de rango 12 permite usar Insignia Explosion con más frecuencia.', 'Stellt MP her. Die Option auf Rang 12 ermöglicht häufigere Insignia Explosion.'),
('Savage Roar engraves Insignias. Build stacks on the target before spending them with Insignia Explosion.', '敵にInsigniaを刻みます。Insignia Explosionで消費する前に、対象のスタックを増やします。', 'Graba Insignias. Acumula marcas en el objetivo antes de gastarlas con Insignia Explosion.', 'Graviert Insignien. Baue Stapel am Ziel auf, bevor du sie mit Insignia Explosion verbrauchst.'),
('Shadowstrike moves behind the target. Its critical-damage option and Ambush Stance support the following attack window.', '対象の背後へ移動します。クリティカルダメージ特化とAmbush Stanceを次の攻撃時間に活用します。', 'Te coloca detrás del objetivo. Su opción de daño crítico y Ambush Stance apoyan los ataques siguientes.', 'Bewegt dich hinter das Ziel. Die kritische Schadensoption und Ambush Stance unterstützen folgende Angriffe.'),
('Ambush gains damage from a back attack. Face the target from behind before using it.', '背面攻撃でダメージが増えます。敵の背後から向き直って使います。', 'Gana daño al atacar por detrás. Colócate y orienta el ataque desde la espalda.', 'Verursacht bei einem Rückenangriff mehr Schaden. Positioniere und richte dich vorher hinter dem Ziel aus.'),
('Heart Gore opens after a critical hit and restores MP. Its critical reset requires the later specialization.', 'クリティカル後に使え、MPも回復します。クリティカルでの再使用リセットは後の特化が必要です。', 'Se habilita tras un crítico y recupera MP. El reinicio por crítico requiere una especialización posterior.', 'Wird nach einem kritischen Treffer verfügbar und stellt MP her. Kritische Resets benötigen die spätere Spezialisierung.'),
('Storm Rampage requires Stagger. Use the opportunity while the target is staggered.', 'スタガー中の対象に使います。使用可能な時間内に攻撃します。', 'Requiere tambaleo. Aprovecha la ventana mientras el objetivo sigue tambaleándose.', 'Benötigt Taumeln. Nutze das Zeitfenster, solange der Zustand anhält.'),
('Whirlwind Slice follows Evasion, or Ambush with its trigger option. It can rotate or stun the target.', '回避後、または発動特化を選んだAmbush後に使え、敵の向き変更やスタンを狙えます。', 'Sigue a evasión o a Ambush con su opción de activación. Puede girar o aturdir al objetivo.', 'Folgt auf Ausweichen oder Ambush mit seiner Auslöseoption. Kann das Ziel drehen oder betäuben.'),
('Flash Slice crosses to the other side of the target and can blind it. Recheck your position afterward.', '対象の反対側へ移動し、暗闇を付与できます。使用後の立ち位置を確認します。', 'Cruza al otro lado del objetivo y puede cegarlo. Revisa tu posición después.', 'Wechselt auf die andere Seite des Ziels und kann blenden. Prüfe danach deine Position.'),
('Infiltrate requires Dodge or flight and moves behind the target. Save it for actual access or repositioning.', '回避後または飛行中に背後へ移動します。接近や位置調整が必要な場面に使います。', 'Requiere esquivar o volar y te coloca detrás. Resérvalo para acceder o recolocarte.', 'Benötigt Ausweichen oder Flug und bewegt dich hinter das Ziel. Hebe es für Zugang oder neue Positionierung auf.'),
('Shadow Fall follows Stun, or a proc against control-immune targets. Its HP absorption option provides recovery.', 'スタン後、または免疫対象への発動時に使います。HP吸収の特化で回復できます。', 'Sigue a un aturdimiento o se activa contra inmunes. Su opción de absorción de HP aporta recuperación.', 'Folgt auf Betäubung oder löst gegen immune Ziele aus. Die HP-Absorption liefert Heilung.'),
('Insignia Explosion scales with target stacks, up to five. Avoid spending a small stack when a full finisher is available.', '対象のInsigniaが最大5スタックまで多いほど強くなります。十分ためられる場面で早く消費しすぎないようにします。', 'Escala con las marcas del objetivo, hasta cinco. Evita gastar pocas si puedes completar el remate.', 'Skaliert mit bis zu fünf Zielstapeln. Verbrauche wenige Stapel nicht vorschnell, wenn ein voller Abschluss möglich ist.'),
('Defiance breaks listed control effects. Keep it available when reaching the target exposes you to counter-control.', '指定された行動阻害を解除します。接近時に反撃の行動阻害を受ける場面で使えるようにします。', 'Rompe los controles indicados. Tenlo disponible cuando acercarte te exponga a control enemigo.', 'Löst die aufgeführten Kontrolleffekte. Halte es bereit, wenn dein Vorstoß gegnerische Kontrolle ermöglicht.'),
])

add('sorcerer', [
('Flame Arrow restores MP and applies Fire Mark through the passive. Its Pyroclasm option adds a fire-damage buff.', 'MPを回復し、パッシブでFire Markを付与します。Pyroclasmの特化は火属性ダメージ強化を追加します。', 'Recupera MP y aplica Fire Mark mediante la pasiva. La opción de Pyroclasm añade daño de fuego.', 'Stellt MP her und bringt über die passive Fertigkeit Fire Mark an. Die Pyroclasm-Option ergänzt einen Feuerbuff.'),
('Ice Chain slows enemies. Select its Winter’s Shackles cooldown option to connect control and damage buffs.', '敵を減速します。Winter’s Shacklesの再使用短縮を選ぶと、減速と攻撃強化をつなげられます。', 'Ralentiza enemigos. Su opción de recarga de Winter’s Shackles enlaza control y mejoras de daño.', 'Verlangsamt Gegner. Die Option für Winter’s Shackles verbindet Kontrolle mit Schadensbuffs.'),
('Firestorm reduces Hellfire cooldown with its rank-12 option. Its MP-cost option supports repeated casts.', 'ランク12の特化でHellfireの再使用を短縮します。MP消費軽減は反復詠唱に役立ちます。', 'Reduce la recarga de Hellfire con su opción de rango 12. Menor coste de MP facilita repetirlo.', 'Verkürzt mit der Rang-12-Option Hellfire. Geringere MP-Kosten helfen bei wiederholter Nutzung.'),
('Bittercold Wind places an area attack at the target and can root enemies. Cast where the group will remain.', '対象位置に範囲攻撃を置き、束縛できます。敵が留まる場所に使います。', 'Coloca un ataque de área en el objetivo y puede inmovilizar. Lánzalo donde permanezcan los enemigos.', 'Platziert einen Flächenangriff am Ziel und kann festhalten. Wirke ihn dort, wo die Gegner bleiben.'),
('Blaze requires Fire Mark and restores MP. Choose delayed damage for offense or HP absorption for solo recovery.', 'Fire Markが条件でMPも回復します。攻撃には遅延ダメージ、ソロ回復にはHP吸収を選べます。', 'Requiere Fire Mark y recupera MP. Elige daño retardado para atacar o absorción de HP para jugar solo.', 'Benötigt Fire Mark und stellt MP her. Wähle verzögerten Schaden oder HP-Absorption für Soloheilung.'),
('Flame Scattershot requires Stagger. A mobile-casting option helps keep attacking during movement.', 'スタガー中の対象に使います。移動可能化の特化で移動中も攻撃しやすくなります。', 'Requiere tambaleo. La opción de lanzamiento móvil ayuda a seguir atacando al desplazarte.', 'Benötigt Taumeln. Die mobile Option hilft bei Angriffen während der Bewegung.'),
('Frost can freeze vulnerable targets and open Frost Burst. Its MP option provides another resource tool.', '凍結が有効な対象に使い、Frost Burstにつなげます。MP特化は追加の資源回復手段です。', 'Puede congelar objetivos vulnerables y habilitar Frost Burst. Su opción de MP añade recuperación de recursos.', 'Kann anfällige Ziele einfrieren und Frost Burst öffnen. Die MP-Option liefert zusätzliche Ressourcen.'),
('Winter’s Shackles slows enemies. Its damage-boost option adds a short offensive window.', '敵を減速します。ダメージ強化の特化で短い攻撃時間を作ります。', 'Ralentiza enemigos. Su opción de aumento de daño crea una ventana ofensiva breve.', 'Verlangsamt Gegner. Die Schadensoption erzeugt ein kurzes offensives Fenster.'),
('Frost Burst requires Frost, or a proc against control-immune targets. Use its actual trigger, not a fixed button order.', 'Frost、または免疫対象への発動が条件です。固定の順番ではなく、実際の発動を見て使います。', 'Requiere Frost o una activación contra inmunes. Sigue la condición real, no un orden fijo.', 'Benötigt Frost oder eine Auslösung gegen immune Ziele. Folge der echten Bedingung statt einer festen Tastenfolge.'),
('Wish of Concentration increases Attack and Accuracy. Use it before charged damage; choose resource options if MP collapses.', '攻撃力と命中を強化します。チャージ攻撃前に使い、MPが続かない場合は資源特化を選びます。', 'Aumenta ataque y precisión. Úsalo antes del daño cargado; elige recursos si el MP se agota.', 'Erhöht Angriff und Genauigkeit. Nutze es vor aufgeladenem Schaden; wähle Ressourcenoptionen bei MP-Problemen.'),
('Hellfire is a charged area attack. Faster or mobile casting trades a specialization choice for a safer cast window.', 'チャージ範囲攻撃です。高速化や移動可能化を選ぶと、安全に詠唱できる時間を確保しやすくなります。', 'Es un ataque de área cargado. Lanzamiento rápido o móvil facilita completar la carga con seguridad.', 'Ist ein aufgeladener Flächenangriff. Schnellere oder mobile Ausführung erleichtert ein sicheres Zeitfenster.'),
('Defiance removes listed control effects. It cannot replace moving out of an incoming attack.', '指定された行動阻害を解除します。危険な攻撃から移動して離れる代わりにはなりません。', 'Elimina los controles indicados. No sustituye salir del alcance de un ataque.', 'Entfernt die aufgeführten Kontrolleffekte. Es ersetzt kein Ausweichen aus einem Angriff.'),
])

add('ranger', [
('Snipe restores MP. Its rank-12 option reduces Deadshot cooldown on hit.', 'MPを回復します。ランク12の特化で命中時にDeadshotの再使用を短縮します。', 'Recupera MP. Su opción de rango 12 reduce la recarga de Deadshot al golpear.', 'Stellt MP her. Die Option auf Rang 12 verkürzt bei Treffern Deadshot.'),
('Tempest Shot attacks a small area around your target. Lower MP cost supports repeated pulls.', '対象周辺の小範囲を攻撃します。MP消費軽減は連続した狩りに役立ちます。', 'Ataca una zona pequeña alrededor del objetivo. Menor coste de MP ayuda en grupos sucesivos.', 'Trifft einen kleinen Bereich um das Ziel. Niedrigere MP-Kosten helfen bei wiederholten Gruppen.'),
('Snare Shot slows enemies and enables Burst Arrow. Use control before its dependent attack.', '敵を減速し、Burst Arrowの条件を作ります。必要な減速を先に付けます。', 'Ralentiza enemigos y habilita Burst Arrow. Aplica el control antes del ataque dependiente.', 'Verlangsamt Gegner und ermöglicht Burst Arrow. Wende die Kontrolle vor dem abhängigen Angriff an.'),
('Marking Shot moves you in the input direction and grants Precision. Use it before Deadshot and watch your landing position.', '入力方向へ移動しPrecisionを得ます。Deadshotの前に使い、移動先の安全も確認します。', 'Te mueve en la dirección indicada y otorga Precision. Úsalo antes de Deadshot y vigila dónde terminas.', 'Bewegt dich in Eingaberichtung und gewährt Precision. Nutze es vor Deadshot und beachte die neue Position.'),
('Drill Dart opens after a critical hit. It applies bleeding and healing reduction, and restores MP if its own hit is critical.', 'クリティカル命中後に使用できます。出血と被回復量減少を付与し、この攻撃もクリティカルならMPを回復します。', 'Se habilita tras un crítico. Aplica sangrado y reducción de curación; recupera MP si su propio golpe es crítico.', 'Öffnet nach einem kritischen Treffer. Verursacht Blutung und Heilreduktion; ein eigener kritischer Treffer stellt MP her.'),
('Arrow Scattershot requires Stagger. Use the boss stagger window rather than forcing it into every opener.', 'スタガーが条件です。毎回の起手に固定せず、ボスのスタガー時間に使います。', 'Requiere tambaleo. Úsalo en esa ventana del jefe, sin forzarlo en cada apertura.', 'Benötigt Taumeln. Nutze das Bossfenster, statt es in jede Eröffnung zu zwingen.'),
('Gale Arrow grants combat speed and damage boosts after hitting. Use it to prepare your attack window.', '命中後に戦闘速度とダメージ強化を得ます。攻撃時間の準備に使います。', 'Otorga velocidad de combate y daño al golpear. Prepara con ella tu ventana de ataque.', 'Gewährt bei Treffern Kampftempo und Schadensbuffs. Bereite damit dein Angriffsfenster vor.'),
('Explosion Trap is placed at your location and triggers when stepped on. Place it on the enemy’s approach path.', '自分の場所に設置し、踏まれると発動します。敵が近づく経路に置きます。', 'Se coloca donde estás y se activa al pisarla. Sitúala en la ruta de aproximación del enemigo.', 'Liegt an deinem Standort und löst beim Betreten aus. Platziere sie im Annäherungsweg des Gegners.'),
('Burst Arrow requires Slow or Root. Confirm the effect is active on the target before using it.', '減速または束縛が条件です。対象にその効果が残っている間に使います。', 'Requiere ralentización o inmovilización. Confirma que el efecto siga activo antes de usarla.', 'Benötigt Verlangsamung oder Festhalten. Prüfe den aktiven Zustand am Ziel vor der Nutzung.'),
('Suppressing Arrow requires Precision and can stun. Marking Shot supplies that buff.', 'Precisionが条件で、スタンを狙えます。Marking Shotで強化を得ます。', 'Requiere Precision y puede aturdir. Marking Shot proporciona la mejora.', 'Benötigt Precision und kann betäuben. Marking Shot liefert diesen Buff.'),
('Deadshot is charged and deals more damage during Precision. Use Marking Shot first and avoid unsafe stationary casts.', 'チャージ攻撃でPrecision中にダメージが増えます。Marking Shotを先に使い、危険な場所で立ち止まらないようにします。', 'Se carga y gana daño durante Precision. Usa Marking Shot primero y evita cargas inmóviles peligrosas.', 'Wird aufgeladen und verursacht mit Precision mehr Schaden. Nutze zuerst Marking Shot und lade nicht an gefährlichen Stellen.'),
('Defiance removes listed control effects. Keep it separate from repeated ranged attacks.', '指定された行動阻害を解除します。遠距離の反復攻撃とは別の操作にします。', 'Elimina los controles indicados. Sepárala de los ataques a distancia repetidos.', 'Entfernt die aufgeführten Kontrolleffekte. Halte es von wiederholten Fernangriffen getrennt.'),
])

add('spiritmaster', [
('Cold Shock restores MP. Use it between spirit actions instead of waiting with no resource recovery.', 'MPを回復します。精霊の行動の合間に使い、資源を回復しながら攻撃します。', 'Recupera MP. Úsalo entre acciones del espíritu en vez de esperar sin recuperar recursos.', 'Stellt MP her. Nutze es zwischen Geistaktionen, statt ohne Ressourcenregeneration zu warten.'),
('Combustion attacks around the target. Choose lower MP cost for sustain or single-target damage for bosses.', '対象周辺を攻撃します。継戦にはMP軽減、ボスには単体向けダメージ特化を選べます。', 'Ataca alrededor del objetivo. Elige menor coste de MP para sostenerte o daño a un objetivo para jefes.', 'Greift um das Ziel an. Wähle geringere MP-Kosten oder Einzelzielschaden für Bosse.'),
('Fire Spirit delivers area damage. Its skill activation option helps produce more spirit-skill opportunities.', '範囲ダメージを与える精霊です。スキル発動率の特化で、精霊スキルの機会を増やします。', 'Aporta daño de área. Su opción de activación genera más oportunidades de habilidades del espíritu.', 'Liefert Flächenschaden. Die Auslöseoption schafft mehr Gelegenheiten für Geistfertigkeiten.'),
('Water Spirit attacks one target and restores your MP when its attacks land. Use it when resources limit the loop.', '単体を攻撃し、命中時に自分のMPを回復します。MP不足で攻撃が止まる場面に役立ちます。', 'Ataca un objetivo y recupera tu MP al golpear. Úsalo cuando los recursos limiten el ciclo.', 'Greift ein Ziel an und stellt bei Treffern deine MP her. Nutze ihn, wenn Ressourcen den Ablauf begrenzen.'),
('Jointstrike: Curse applies damage over time and reduces damage dealt to you. Its coordinated attack depends on the active spirit.', '持続ダメージを付け、自分へのダメージを減らします。連携攻撃の内容は現在の精霊で変わります。', 'Aplica daño periódico y reduce el daño hacia ti. El ataque coordinado depende del espíritu activo.', 'Verursacht Schaden über Zeit und verringert Schaden gegen dich. Der gemeinsame Angriff hängt vom aktiven Geist ab.'),
('Rapid Scattershot requires Stagger. Use it during the stagger opportunity while preserving summon management.', 'スタガーが条件です。精霊管理を続けながら、その時間帯に使います。', 'Requiere tambaleo. Aprovecha la ventana manteniendo la gestión de invocaciones.', 'Benötigt Taumeln. Nutze das Fenster und behalte die Beschwörungsverwaltung bei.'),
('Earth Spirit builds threat and has defensive stat scaling. Watch its health when using it to hold an enemy.', '敵対値を増やし、防御向けに成長します。敵を引き受けさせる際は精霊のHPも見ます。', 'Genera amenaza y escala defensivamente. Vigila su HP si lo usas para retener enemigos.', 'Erzeugt Bedrohung und wächst defensiv. Beobachte seine HP, wenn er Gegner halten soll.'),
('Dimensional Control briefly opens after a summon or spirit-skill activation. Use the available window promptly; it also restores MP.', '精霊召喚や精霊スキル発動後の短い使用可能時間に使います。MPも回復します。', 'Se abre brevemente tras una invocación o activación de habilidad del espíritu. Aprovecha la ventana; también recupera MP.', 'Öffnet kurz nach Beschwörung oder Geistfertigkeit. Nutze das verfügbare Fenster; es stellt auch MP her.'),
('Wind Spirit supplies area damage and healing to you. It is useful when recovery matters more than a shorter summon sequence.', '範囲攻撃と自分の回復を行います。召喚回数を減らすより回復が必要な場面で役立ちます。', 'Aporta daño de área y te cura. Sirve cuando recuperarte importa más que acortar las invocaciones.', 'Liefert Flächenschaden und heilt dich. Hilft, wenn Heilung wichtiger als eine kürzere Beschwörungsfolge ist.'),
('Soul’s Cry fears vulnerable enemies. Keep it available for control instead of burying it in boss damage.', '恐怖が有効な敵を制御します。ボス用の反復攻撃に埋め込まず、必要な時に使います。', 'Causa miedo a enemigos vulnerables. Resérvalo para control en vez de incluirlo en daño repetido al jefe.', 'Versetzt anfällige Gegner in Furcht. Halte es für Kontrolle statt im wiederholten Bossschaden bereit.'),
('Elemental Fusion requires Four Elements from four spirit-skill activations. Spend it before further activations are wasted.', '精霊スキル4回分でFour Elementsを得ると使えます。追加の獲得が止まるため、使える時に消費します。', 'Requiere Four Elements tras cuatro activaciones de habilidades de espíritu. Gástalo antes de desperdiciar nuevas activaciones.', 'Benötigt Four Elements aus vier Geistfertigkeits-Auslösungen. Verbrauche es, bevor weitere Auslösungen verloren gehen.'),
('Defiance removes listed control effects. It is independent of the spirit’s attack sequence.', '指定された行動阻害を解除します。精霊の攻撃順とは独立して使います。', 'Elimina los controles indicados. Úsalo de forma independiente del ataque del espíritu.', 'Entfernt die aufgeführten Kontrolleffekte. Nutze es unabhängig von der Angriffsfolge des Geists.'),
])

add('cleric', [
('Earth’s Retribution restores MP. Its Discharge cooldown option brings Bolt back sooner.', 'MPを回復します。Dischargeの再使用短縮特化でBoltを早く使えるようにします。', 'Recupera MP. Su opción de recarga mediante Discharge permite reutilizar Bolt antes.', 'Stellt MP her. Die Discharge-Option lässt Bolt früher wieder verfügbar werden.'),
('Judgment Thunder hits around the target. Use it when healing is stable and the damage window is safe.', '対象周辺を攻撃します。回復が安定している安全な攻撃時間に使います。', 'Golpea alrededor del objetivo. Úsalo cuando la curación esté estable y puedas atacar seguro.', 'Trifft um das Ziel herum. Nutze es bei stabiler Heilung und einem sicheren Angriffsfenster.'),
('Debilitating Mark reduces enemy damage output and applies damage over time. Its defense-reduction option adds offense.', '敵の与ダメージを下げ、持続ダメージを付けます。防御低下の特化は攻撃面も補います。', 'Reduce el daño enemigo y aplica daño periódico. Su opción de reducción de defensa añade presión ofensiva.', 'Senkt gegnerischen Schaden und verursacht Schaden über Zeit. Die Verteidigungsoption ergänzt die Offensive.'),
('Divine Aura stays where summoned and attacks a selected target. Place it where it can keep contributing during the fight.', '召喚位置に留まり、選んだ対象を攻撃します。戦闘中も攻撃が届く場所に置きます。', 'Permanece donde la invocas y ataca al objetivo elegido. Colócala donde pueda seguir contribuyendo.', 'Bleibt am Beschwörungsort und greift das gewählte Ziel an. Platziere sie für anhaltenden Beitrag im Kampf.'),
('Chain of Torment reduces enemy damage tolerance and opens Condemnation on that target. Refresh the debuff before it expires.', '敵のダメージ耐性を下げ、Condemnationの条件を作ります。減益の切れ目を短くします。', 'Reduce la tolerancia al daño y habilita Condemnation. Renueva el perjuicio antes de que expire.', 'Senkt Schadenstoleranz und öffnet Condemnation am Ziel. Erneuere den Effekt vor seinem Ablauf.'),
('Lightning Strike Scattershot requires Stagger. Use it during a safe stagger window without delaying needed healing.', 'スタガーが条件です。必要な回復を遅らせず、安全な時間帯に使います。', 'Requiere tambaleo. Úsalo en una ventana segura sin retrasar curaciones necesarias.', 'Benötigt Taumeln. Nutze ein sicheres Fenster, ohne nötige Heilung zu verzögern.'),
('Light of Regeneration provides party healing over time. Start it before damage accumulates, then add direct healing if needed.', 'パーティを継続回復します。被ダメージが重なる前に使い、必要に応じて即時回復を追加します。', 'Cura periódicamente al grupo. Actívala antes de acumular daño y añade curación directa si hace falta.', 'Heilt die Gruppe über Zeit. Starte vor anwachsenden Schäden und ergänze bei Bedarf direkte Heilung.'),
('Condemnation requires Chain of Torment. A later critical-reset option changes how often you can repeat it.', 'Chain of Tormentが条件です。後のクリティカルリセット特化で繰り返せる頻度が変わります。', 'Requiere Chain of Torment. Una opción posterior de reinicio por crítico cambia su repetición.', 'Benötigt Chain of Torment. Eine spätere kritische Reset-Option verändert die Wiederholbarkeit.'),
('Healing Light heals you and the party member with the lowest HP in range. It is not a freely aimed single-ally heal.', '範囲内で自分とHPが最も低いパーティメンバーを回復します。任意の味方一人を狙う回復ではありません。', 'Te cura y cura al miembro con menos HP dentro del alcance. No apunta libremente a un aliado concreto.', 'Heilt dich und das Gruppenmitglied mit den niedrigsten HP in Reichweite. Es ist keine frei gezielte Einzelheilung.'),
('Radiant Recovery heals the party and removes one debuff by default. Keep it ready for removable harmful effects.', '基本効果でパーティを回復し、減益を1つ解除します。解除可能な有害効果に使えるようにします。', 'Cura al grupo y elimina un perjuicio de base. Tenla preparada para efectos dañinos eliminables.', 'Heilt die Gruppe und entfernt bereits standardmäßig einen negativen Effekt. Halte es für entfernbare Effekte bereit.'),
('Bolt is charged area damage. Faster casting helps complete it between mechanics; cancel offense for urgent recovery.', 'チャージ範囲攻撃です。高速化でギミックの合間に完了しやすくなりますが、緊急回復を優先します。', 'Es daño de área cargado. Lanzar más rápido ayuda entre mecánicas; interrumpe daño para recuperar al grupo.', 'Verursacht aufgeladenen Flächenschaden. Schnellere Ausführung hilft zwischen Mechaniken; unterbrich für dringende Heilung.'),
('Defiance breaks listed control on yourself. Radiant Recovery handles removable party debuffs; they have different jobs.', '自分の指定された行動阻害を解除します。味方の減益を解除するRadiant Recoveryとは役割が異なります。', 'Rompe los controles indicados sobre ti. Radiant Recovery elimina perjuicios del grupo; cumplen tareas distintas.', 'Löst die aufgeführten Kontrolleffekte bei dir. Radiant Recovery entfernt Gruppeneffekte; die Aufgaben unterscheiden sich.'),
])

add('chanter', [
('Onslaught restores MP. Its rank-12 option shortens Spinning Strike cooldown on hit.', 'MPを回復します。ランク12の特化で命中時にSpinning Strikeの再使用を短縮します。', 'Recupera MP. Su opción de rango 12 reduce la recarga de Spinning Strike al golpear.', 'Stellt MP her. Die Option auf Rang 12 verkürzt bei Treffern Spinning Strike.'),
('Incandescent Blow attacks nearby enemies. Lower MP cost keeps ordinary attacks sustainable.', '近くの敵を攻撃します。MP消費軽減で通常の攻撃を継続しやすくなります。', 'Ataca enemigos cercanos. Menor coste de MP ayuda a sostener ataques ordinarios.', 'Trifft nahe Gegner. Niedrigere MP-Kosten halten normale Angriffe aufrecht.'),
('Rushing Smash closes distance and restores MP. The on-kill reset helps repeated small pulls.', '接近しMPを回復します。撃破時リセットは連続した小規模の狩りに役立ちます。', 'Cierra distancia y recupera MP. El reinicio al matar ayuda en grupos pequeños sucesivos.', 'Überbrückt Distanz und stellt MP her. Der Kill-Reset hilft bei aufeinanderfolgenden kleinen Gruppen.'),
('Impactful Crush opens Dark Crush briefly. Follow with Dark Crush before using another trigger.', '短時間Dark Crushを使用可能にします。別の起点を使う前にDark Crushで追撃します。', 'Habilita Dark Crush brevemente. Síguelo con Dark Crush antes de gastar otro activador.', 'Öffnet Dark Crush kurzzeitig. Nutze den Folgeangriff, bevor du einen weiteren Auslöser verbrauchst.'),
('Dark Crush is the triggered attack. Wait for its cooldown until the cooldown-removal specialization is selected.', '起点から発動する攻撃です。再使用時間削除の特化を選ぶまではクールダウンを待ちます。', 'Es el ataque activado. Espera su recarga hasta seleccionar la especialización que la elimina.', 'Ist der ausgelöste Angriff. Warte auf seine Abklingzeit, bis die entfernende Spezialisierung gewählt ist.'),
('Gust Rampage requires Stagger. Use it during stagger without losing access to party recovery.', 'スタガーが条件です。その間もパーティ回復を使えるようにして攻撃します。', 'Requiere tambaleo. Úsalo sin perder acceso a la recuperación del grupo.', 'Benötigt Taumeln. Nutze es, ohne den Zugriff auf Gruppenheilung zu verlieren.'),
('Heat Wave Blow follows Parry, or Rushing Smash with its trigger option. It can seal the enemy.', 'パリィ後、または発動特化を選んだRushing Smash後に使用でき、敵を封印できます。', 'Sigue a parar o a Rushing Smash con su opción de activación. Puede sellar al enemigo.', 'Folgt auf Parieren oder Rushing Smash mit seiner Auslöseoption. Kann den Gegner versiegeln.'),
('Recuperation heals and removes one debuff, then continues healing over time. More cleansing is a specialization choice.', '回復と減益1つの解除を行い、その後も継続回復します。解除数の追加は特化で選べます。', 'Cura, elimina un perjuicio y sigue curando periódicamente. Más limpieza es una opción de especialización.', 'Heilt, entfernt einen negativen Effekt und heilt weiter über Zeit. Mehr Reinigung ist eine Spezialisierungsoption.'),
('Tremor Crush requires Dodge or flight and approaches the target. Keep its movement under manual control.', '回避後または飛行中に接近します。移動先を判断して手動で使います。', 'Requiere esquivar o volar y te aproxima. Controla manualmente el desplazamiento.', 'Benötigt Ausweichen oder Flug und nähert sich dem Ziel. Steuere die Bewegung manuell.'),
('Wave Blow follows Stun, or a proc against control-immune targets. Use the actual opportunity.', 'スタン後、または免疫対象への発動時に使います。実際に使える機会を見て追撃します。', 'Sigue a un aturdimiento o se activa contra inmunes. Usa la oportunidad real.', 'Folgt auf Betäubung oder löst gegen immune Ziele aus. Nutze die tatsächliche Gelegenheit.'),
('Spinning Strike grants a critical-damage buff and briefly opens Dark Crush. Its single-target option suits bosses.', 'クリティカルダメージ強化と短いDark Crushの使用時間を得ます。単体向け特化はボスに適します。', 'Otorga daño crítico y habilita Dark Crush brevemente. La opción de objetivo único sirve para jefes.', 'Gewährt kritischen Schaden und öffnet Dark Crush kurz. Die Einzelzieloption eignet sich für Bosse.'),
('Defiance removes listed control on yourself. Keep party healing on separate controls as well.', '自分の指定された行動阻害を解除します。パーティ回復も別の操作に保ちます。', 'Elimina los controles indicados sobre ti. Mantén también la curación del grupo en controles separados.', 'Entfernt die aufgeführten Kontrolleffekte bei dir. Halte auch Gruppenheilung separat erreichbar.'),
])

(ROOT / 'src/content/class-skill-focus.json').write_text(json.dumps(rows, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print('Authored functional notes for 96 active skills in four languages.')
