from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[4]
LOCALES=['en','ja','es','de']
def save(path,data):path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def row(en,ja,es,de):return dict(zip(LOCALES,[en,ja,es,de]))
PAGES={
'settings':{
 'labels':row('Settings & controls','設定と操作','Ajustes y controles','Einstellungen und Steuerung'),
 'quick':row('Start with targeting, movement and potion auto-use, then place reactive skills on reachable keys. Adjust HUD and graphics in a repeatable combat scene; save a setting only after testing its effect.','ターゲット選択、移動、ポーション自動使用から調整し、反応が必要なスキルを押しやすいキーに置きます。同じ戦闘場面でHUDと画面設定を比較し、効果を確認してから保存します。','Empieza por objetivos, movimiento y pociones automáticas; asigna las habilidades reactivas a teclas accesibles. Compara HUD y gráficos en la misma escena de combate y prueba cada cambio.','Beginne mit Zielwahl, Bewegung und automatischen Tränken. Lege reaktive Fertigkeiten auf erreichbare Tasten. Vergleiche HUD und Grafik in derselben Kampfszene und prüfe jede Änderung.'),
 'next':'guide','related':['guide','macro-guide','download'],
 'sections':[
 ('control-mode',row('Choose a control mode','操作モードを選ぶ','Elige un modo de control','Steuerungsmodus wählen'),row('Open Settings → Combat and compare the available AION 1 and AION 2 control modes. Try camera movement, selecting an enemy and turning away from it before combat. Keep the mode in which you can move and use your emergency buttons without losing sight of the fight. Check the current bindings rather than assuming a key from another setup is still assigned.','設定 → CombatでAION 1とAION 2の操作モードを比較します。戦闘前にカメラ移動、敵の選択、視点を反転する操作を試してください。戦闘を見失わずに移動と緊急スキルを使えるモードを選びます。他の設定で使っていたキーが現在も割り当てられているとは限らないため、実際のキー設定を確認してください。','Abre Ajustes → Combat y compara los modos AION 1 y AION 2. Antes de luchar, prueba la cámara, selecciona un enemigo y gira. Elige el modo que te permita moverte y usar acciones de emergencia sin perder la pelea de vista. Comprueba las asignaciones actuales de teclas.','Öffne Einstellungen → Combat und vergleiche AION 1 mit AION 2. Teste vor dem Kampf Kamerabewegung, Zielwahl und das Umdrehen. Wähle den Modus, in dem du dich bewegen und Notfalltasten bedienen kannst, ohne den Kampf aus den Augen zu verlieren. Prüfe die tatsächlichen Tastenbelegungen.')),
 ('targeting-and-pursuit',row('Target scanning and pursuit','ターゲット検索と追従','Búsqueda y seguimiento de objetivos','Zielsuche und Verfolgung'),row('Under Combat → Target Scanning, inspect the preferred search direction. Front of camera helps select enemies you are looking toward. Under Combat → Controls, inspect pursuit with skill activation. Melee pursuit can help close distance; a ranged character may prefer it off to avoid walking into the pack. Test selecting a nearer enemy with another enemy behind you, then cast while outside range and observe whether your character moves.','Combat → Target Scanningで検索方向を確認します。Front of cameraはカメラの前方にいる敵を選ぶための設定です。Combat → Controlsではスキル使用時の追従を確認します。近接職では接近に便利ですが、遠距離職は敵集団へ歩かないよう無効にする選択肢があります。背後にも敵がいる状況で選択を試し、射程外からスキルを使ったときの移動も確認します。','En Combat → Target Scanning, revisa la dirección preferida. Front of camera busca enemigos hacia los que miras. En Combat → Controls, comprueba la persecución al activar habilidades. Puede ayudar en cuerpo a cuerpo, pero un personaje a distancia quizá prefiera desactivarla para no entrar en el grupo enemigo. Prueba objetivos delante y detrás y observa qué ocurre al lanzar fuera de alcance.','Prüfe unter Combat → Target Scanning die Suchrichtung. Front of camera richtet die Suche auf den Kamerablick. Unter Combat → Controls findest du die Verfolgung bei Fertigkeitsaktivierung. Im Nahkampf kann sie beim Annähern helfen; im Fernkampf kann Abschalten unbeabsichtigtes Laufen in Gegner verhindern. Teste Ziele vor und hinter dir sowie einen Angriff außerhalb der Reichweite.')),
 ('potions-and-loot',row('Potion auto-use and loot','ポーション自動使用と拾得','Pociones automáticas y botín','Automatische Tränke und Beute'),row('Combat → Auto Use controls automatic HP consumables. Choose a threshold that fits the damage you take and your potion supply; leave manual access available. A high threshold can consume potions during minor damage. In Combat → Looting, review selections before enabling automatic rules. Protect equipment needed by quests or recipes and read extraction selections before confirming disposal.','Combat → Auto UseでHP回復品の自動使用を設定します。受けるダメージと所持数に合わせて条件を決め、手動使用のキーも残します。高い発動条件では小さな被害でも消費が続くことがあります。Combat → Lootingの自動処理は対象を確認してから有効にします。クエストやレシピで使う装備を保護し、抽出前に選択一覧を読みます。','Combat → Auto Use controla consumibles de HP automáticos. Elige un umbral acorde al daño y tus reservas, manteniendo acceso manual. Un umbral alto puede consumir pociones por daños pequeños. Revisa Combat → Looting antes de activar reglas automáticas. Protege equipo de misiones o recetas y comprueba la selección antes de extraerlo.','Combat → Auto Use steuert automatische HP-Verbrauchsgegenstände. Passe die Schwelle an Schaden und Vorrat an und behalte manuellen Zugriff. Eine hohe Schwelle kann bei kleinen Treffern Tränke verbrauchen. Prüfe Combat → Looting vor automatischen Regeln. Schütze Quest- und Rezeptausrüstung und kontrolliere die Auswahl vor dem Zerlegen.')),
 ('keybinds-and-hud',row('Key bindings and a readable HUD','キー設定と見やすいHUD','Teclas y HUD legible','Tasten und lesbares HUD'),row('Place movement, dodge or block, interrupt, healing and other encounter reactions on separate reachable controls. Use the built-in macro for a tested repeatable attack stack, not as your only access to a recovery skill. Open HUD Edit and keep HP, MP, target information and party frames readable. In Info Display → Common, adjust nameplates. Try the layout in combat: your eyes should find health and the next mechanic without searching across overlapping panels.','移動、防御、妨害、回復など状況に応じる操作は押しやすい別キーに置きます。ゲーム内マクロは確認済みの繰り返し攻撃に使い、回復の唯一の操作手段にはしません。HUD EditでHP、MP、対象情報、パーティー表示を見やすくします。Info Display → Commonでは名前表示を調整できます。戦闘中にHPとギミックをすぐ確認できるか、パネルの重なりも含めて試してください。','Pon movimiento, defensa, interrupción y recuperación en controles independientes y accesibles. Usa el macro integrado para ataques repetibles ya probados, sin perder acceso directo a curas. En HUD Edit, mantén legibles HP, MP, objetivo y grupo. Ajusta nombres en Info Display → Common y prueba que los paneles no oculten mecánicas durante el combate.','Lege Bewegung, Abwehr, Unterbrechung und Heilung auf getrennte erreichbare Tasten. Nutze das eingebaute Makro für geprüfte wiederholbare Angriffe, nicht als einzigen Zugriff auf Heilung. Halte HP, MP, Ziel und Gruppenfenster in HUD Edit lesbar. Passe Namen unter Info Display → Common an und prüfe im Kampf, ob Fenster Mechaniken verdecken.')),
 ('graphics-and-crowds',row('Graphics and crowded fights','画面設定と混雑した戦闘','Gráficos y combates concurridos','Grafik und volle Kämpfe'),row('For large groups, inspect identical player appearance and other-player effect visibility. Limit effects to self or party when visual clutter hides mechanics. Compare lower shadows and reflections in the same scene. Upscaling options depend on your GPU and the options offered by the client; compare image clarity as well as frame rate. No single preset guarantees an FPS increase on every PC. Keep enemy warnings and useful party effects visible.','大人数の場面ではプレイヤー外見の簡略化と他プレイヤーの効果表示を確認します。効果でギミックが見えない場合は自分やパーティーに絞ります。同じ場面で影と反射を下げた結果を比較してください。アップスケーリングはGPUとクライアントの選択肢に依存するため、フレームレートだけでなく文字や輪郭の明瞭さも確認します。すべてのPCで改善する設定はありません。敵の警告と必要な味方の効果は見える状態を保ちます。','En grupos grandes, revisa la apariencia simplificada de jugadores y los efectos ajenos. Limítalos a ti o al grupo si ocultan mecánicas. Compara sombras y reflejos bajos en la misma escena. El escalado depende de GPU y cliente: compara claridad y FPS. Ningún ajuste garantiza mejoras en todos los equipos; conserva visibles las advertencias y los efectos útiles.','Prüfe bei großen Gruppen vereinheitlichte Spieleroptik und fremde Effekte. Beschränke Effekte bei verdeckten Mechaniken auf dich oder die Gruppe. Vergleiche niedrigere Schatten und Reflexionen in derselben Szene. Upscaling hängt von GPU und Client ab; prüfe Bildklarheit und FPS. Kein Profil garantiert auf jedem PC mehr Leistung. Warnungen und hilfreiche Gruppeneffekte müssen sichtbar bleiben.')),
 ('test-your-settings',row('Test before keeping the changes','変更を残す前に試す','Prueba antes de guardar','Änderungen vor dem Behalten testen'),row('Record your starting settings and change one group at a time. Repeat a short encounter using the same camera angle and route. Check unintended movement, target selection, potion consumption, readable warnings and frame stability. If a change makes a reaction harder, restore that setting first. Repeat the test after changing control mode or moving an emergency skill. A smooth empty field does not tell you how a crowded boss fight will behave.','変更前の設定を記録し、一度に一種類ずつ調整します。同じカメラ角度と経路で短い戦闘を繰り返してください。意図しない移動、ターゲット選択、ポーション消費、警告の見やすさ、動作の安定を確認します。反応が難しくなった設定は元に戻します。操作モードや緊急スキルの位置を変えたら再試験します。人のいない場所の滑らかさだけでは混雑したボス戦の状態は判断できません。','Anota la configuración inicial y cambia un grupo cada vez. Repite un combate corto con la misma cámara y ruta. Comprueba movimiento involuntario, objetivos, consumo de pociones, avisos y estabilidad. Revierte primero lo que dificulte reaccionar y vuelve a probar después de cambiar el modo o una habilidad de emergencia. Un campo vacío no representa un jefe concurrido.','Notiere die Ausgangswerte und ändere jeweils eine Gruppe. Wiederhole einen kurzen Kampf mit gleicher Kamera und Route. Prüfe unbeabsichtigte Bewegung, Zielwahl, Trankverbrauch, Warnungen und Stabilität. Stelle Änderungen zurück, die Reaktionen erschweren. Teste nach Moduswechsel oder versetzter Notfalltaste erneut. Ein leeres Feld zeigt nicht die Leistung bei einem vollen Bosskampf.')),
 ]},
'gear-progression':{
 'labels':row('Gear progression','装備の成長','Progresión de equipo','Ausrüstungsfortschritt'),
 'quick':row('At level 45, finish campaign unlocks and accessible exploration, then identify the entry requirement for your next activity. Separate gear score from Combat Power; preview upgrade costs and results before committing materials.','45になったらストーリーの解放条件と利用可能な探索を完了し、次の活動の入場条件を確認します。装備スコアと戦闘力を分けて考え、素材を使う前に強化コストと結果を確認してください。','Al llegar a 45, termina desbloqueos de campaña y exploración accesible. Identifica el requisito de tu próxima actividad, distingue puntuación de equipo y poder de combate y revisa costes antes de gastar.','Erledige auf Stufe 45 Kampagnenfreischaltungen und erreichbare Erkundung. Bestimme die Voraussetzung deiner nächsten Aktivität. Trenne Ausrüstungswertung und Kampfkraft und prüfe Kosten vor dem Materialverbrauch.'),
 'next':'daily-weekly-checklist','related':['leveling','builds','crafting'],
 'sections':[
 ('three-progression-numbers',row('Level, gear score and Combat Power','レベル・装備スコア・戦闘力','Nivel, equipo y poder de combate','Stufe, Ausrüstungswertung und Kampfkraft'),row('Character level records experience progression. Gear score or item level describes equipment progression and can be an entry requirement. Combat Power includes wider character strength, including skills and other growth systems. Read the exact number used by the activity before upgrading. Raising Combat Power does not complete a missing campaign quest, and reaching level 45 does not automatically satisfy an equipment gate.','キャラクターレベルは経験値の進行を表します。装備スコアやアイテムレベルは装備の成長を表し、入場条件に使われることがあります。戦闘力にはスキルなど他の成長要素も含まれます。強化前に、その活動が要求している数値を確認してください。戦闘力を上げても未完了のストーリーは完了せず、45到達だけでは装備条件を満たせません。','El nivel representa experiencia. La puntuación o nivel de objeto describe el equipo y puede limitar entradas. El poder de combate incluye habilidades y otros sistemas. Lee qué cifra exige la actividad: aumentar poder no completa una misión pendiente y llegar a 45 no satisface automáticamente un requisito de equipo.','Die Charakterstufe beschreibt Erfahrung. Ausrüstungswertung oder Gegenstandsstufe erfassen Ausrüstung und können den Zugang begrenzen. Kampfkraft umfasst auch Fertigkeiten und andere Systeme. Prüfe die verlangte Zahl: Mehr Kampfkraft erledigt keine fehlende Quest, und Stufe 45 erfüllt nicht automatisch eine Ausrüstungsgrenze.')),
 ('fresh-level-45',row('Your first steps at 45','45到達直後の手順','Primeros pasos al nivel 45','Erste Schritte auf Stufe 45'),row('Finish the remaining main story and review useful quest rewards. Clear accessible sealed dungeons and strongholds you skipped, and collect nearby feathers while following those objectives. Review the skill points and Daevanion resources obtained from exploration before spending more equipment materials. Open your next activity’s panel, select its difficulty and check unlock, equipment and reward requirements separately. Choose an activity you can complete reliably.','残りのメインストーリーを完了し、役立つクエスト報酬を確認します。未完了で入れる封印ダンジョンや拠点を進め、経路上の羽も回収します。さらに装備素材を使う前に、探索で得たスキルポイントとディーヴァニオン素材を見直してください。次の活動の画面で難易度を選び、解放、装備、報酬の条件を別々に確認します。安定して完了できる活動を選びましょう。','Termina la historia pendiente y revisa sus recompensas. Completa mazmorras selladas y fortalezas accesibles que omitiste; recoge plumas cercanas. Revisa puntos de habilidad y recursos de Daevanion obtenidos explorando antes de invertir más en equipo. Selecciona la dificultad de la próxima actividad y comprueba desbloqueo, equipo y recompensa por separado.','Schließe die übrige Hauptgeschichte ab und prüfe nützliche Questbelohnungen. Erledige ausgelassene erreichbare versiegelte Dungeons und Festungen und sammle nahe Federn. Prüfe Erkundungsressourcen für Fertigkeiten und Daevanion vor weiterer Ausrüstungsinvestition. Wähle im Aktivitätsfenster die Schwierigkeit und prüfe Freischaltung, Ausrüstung und Belohnungen getrennt.')),
 ('growth-and-enhancement',row('Growth and enhancement are separate','成長と強化を分ける','Crecimiento y mejora son distintos','Wachstum und Verstärkung unterscheiden'),row('Inspect each item’s upgrade panel rather than assuming all equipment uses one rule. Compare the current item with the preview: stat changes, required materials, currency and any failure condition shown. Upgrade one piece for a specific purpose, such as a weapon improvement or a missing entry requirement. Keep enough materials for that operation; do not spread your supply across several temporary pieces without checking how much progress each buys.','すべての装備に同じルールがあると考えず、各アイテムの成長・強化画面を確認します。現在の装備とプレビューを比較し、能力値、必要素材、通貨、失敗時の条件を読みます。武器の改善や入場条件など、一つの目的に合わせて強化してください。一回の操作に必要な素材を確保し、効果を確認せずに複数の仮装備へ分散しないようにします。','Consulta el panel de cada objeto: no todos usan la misma regla. Compara estadísticas, materiales, moneda y condiciones de fallo de la vista previa. Mejora una pieza para resolver una necesidad concreta, como daño del arma o una entrada. Reserva lo necesario para esa operación antes de repartir materiales entre varias piezas temporales.','Prüfe das Verbesserungsfenster jedes Gegenstands, statt einheitliche Regeln anzunehmen. Vergleiche Vorschauwerte, Materialien, Währung und angezeigte Fehlschlagsbedingungen. Verbessere ein Teil für einen konkreten Zweck, etwa Waffenschaden oder Zugang. Reserviere dafür genug Material, bevor du es auf mehrere vorläufige Teile verteilst.')),
 ('belt-and-amulet',row('Belt and amulet upgrades','ベルトと護符の更新','Cinturón y amuleto','Gürtel und Amulett'),row('Belt and amulet progression can involve enhancement followed by a Substance Morph recipe. Open that recipe and match the exact input item, its required enhancement and all materials. Remove the item from equipped presets when the recipe requires an unequipped input. Check the output before accepting: a matching appearance or name alone is not enough. Keep the input until the recipe is ready, rather than dismantling it during inventory cleanup.','ベルトと護符は強化後にSubstance Morphのレシピで更新する場合があります。対象レシピを開き、入力アイテム、必要強化段階、素材を照合します。未装備の入力が必要なら、装備プリセットからも外してください。見た目や似た名称だけでは判断せず、確定前に出力を確認します。レシピが完成するまで入力装備を保管し、整理中に抽出しないようにします。','El cinturón y amuleto pueden mejorar mediante refuerzo seguido de una receta de Substance Morph. Comprueba objeto exacto, refuerzo exigido y materiales. Retíralo de los conjuntos equipados cuando la receta exija una pieza sin equipar. Revisa el resultado antes de aceptar y conserva la pieza de entrada hasta tener lista la receta.','Gürtel und Amulett können nach Verstärkung über ein Substance-Morph-Rezept weiterentwickelt werden. Prüfe genauen Eingangsgegenstand, erforderliche Verstärkung und Materialien. Entferne ihn bei Bedarf aus ausgerüsteten Vorlagen. Kontrolliere das Ergebnis vor der Bestätigung und bewahre den Eingang auf, bis das Rezept bereit ist.')),
 ('sockets-binding-and-transfer',row('Sockets, binding and transfer','装着・バインド・転移','Ranuras, vinculación y transferencia','Sockel, Bindung und Übertragung'),row('Check the available Manastone and Theostone slots on your actual weapon or armor before buying stones. Read the binding or reroll confirmation separately from enhancement: cost and affected stats are different decisions. For transfer, select the actual source and destination and inspect exactly which progress is retained. Never dispose of the old item before confirming the result. An item’s trade, storage and extraction permissions are separate flags; read them before making an irreversible inventory choice.','魔石やTheostoneを購入する前に、実際の武器・防具の枠を確認します。バインドや再抽選は強化とは別に確認し、費用と変化する能力値を読みます。転移では実際の元装備と移転先を選び、何が引き継がれるかを確認してください。結果を確かめる前に元装備を処分しません。取引、倉庫、抽出の可否は別々の条件なので、戻せない操作の前に確認します。','Antes de comprar piedras, revisa las ranuras de Manastone y Theostone del equipo real. Lee la confirmación de vinculación o cambio de atributos separada de la mejora. Para transferir, selecciona origen y destino y comprueba qué progreso se conserva. No destruyas el objeto antiguo antes de confirmar el resultado. Comercio, almacenamiento y extracción tienen permisos separados.','Prüfe tatsächliche Manastone- und Theostone-Plätze vor dem Steinkauf. Lies Bindungs- und Neuwürfelkosten getrennt von der Verstärkung. Wähle bei Übertragung Quelle und Ziel und prüfe, welcher Fortschritt erhalten bleibt. Entsorge das alte Teil erst nach Prüfung des Ergebnisses. Handel, Lagerung und Zerlegen haben getrennte Berechtigungen.')),
 ('next-upgrade',row('Choose the next useful upgrade','次に役立つ強化を決める','Elige la siguiente mejora útil','Die nächste sinnvolle Verbesserung wählen'),row('If entry is locked, resolve the listed requirement. If a boss kills you, review attacks, positioning and recovery before adding gear score. If damage or MP is the problem, inspect skills, specializations and Daevanion as well as equipment. Save crafting materials for a named recipe and compare its cost with the reward route you can already complete. After upgrading, reopen the activity panel and retest the same encounter to confirm the blocker is resolved.','入場できない場合は表示条件を満たします。ボスで倒れる場合は装備スコアを増やす前に攻撃、位置取り、回復を見直します。火力やMPが問題なら、装備に加えてスキル、特化、ディーヴァニオンを確認してください。製作素材は目的のレシピのために保存し、現在完了できる報酬ルートと費用を比較します。強化後は活動画面と同じ戦闘を再確認し、障害が解消したかを確かめます。','Resuelve el requisito indicado si la entrada está bloqueada. Si el jefe te mata, revisa ataques, posición y recuperación antes de sumar puntuación. Para daño o MP, revisa habilidades, especializaciones y Daevanion. Guarda materiales para una receta concreta y compara su coste con recompensas accesibles. Tras mejorar, comprueba de nuevo el panel y el mismo encuentro.','Erfülle bei gesperrtem Zugang die angezeigte Bedingung. Prüfe bei Bossniederlagen Angriffe, Position und Erholung vor zusätzlicher Ausrüstungswertung. Untersuche bei Schaden oder MP auch Fertigkeiten, Spezialisierungen und Daevanion. Spare Material für ein konkretes Rezept und vergleiche erreichbare Belohnungen. Prüfe nach der Verbesserung dasselbe Fenster und denselben Kampf erneut.')),
 ]},
'daily-weekly-checklist':{
 'labels':row('Daily & weekly checklist','毎日・毎週のチェックリスト','Lista diaria y semanal','Tages- und Wochenliste'),
 'quick':row('At 45, open Journal → Duty and inspect its available missions. Before a limited activity, check entry cost, reward allowance and its displayed reset. Keep one-time exploration, regenerating energy and periodic reward counters separate.','45になったらJournal → Dutyで利用可能な任務を確認します。回数制限のある活動では参加費、報酬枠、表示された更新時刻を読み、一度限りの探索、自動回復するエネルギー、周期的な報酬枠を分けて扱います。','Al llegar a 45, abre Journal → Duty y revisa misiones. Antes de una actividad limitada, comprueba coste, recompensas restantes y reinicio indicado. Separa exploración única, energía regenerable y contadores periódicos.','Öffne auf Stufe 45 Journal → Duty und prüfe Missionen. Kontrolliere vor begrenzten Aktivitäten Eintrittskosten, Belohnungsanzahl und angezeigten Reset. Trenne einmalige Erkundung, regenerierende Energie und periodische Belohnungszähler.'),
 'next':'gear-progression','related':['guide','leveling','crafting'],
 'sections':[
 ('different-counters',row('Use the right counter','確認するカウンターを分ける','Usa el contador correcto','Den richtigen Zähler verwenden'),row('A daily and weekly checklist organizes your available activities; it is not a separate game mode. A campaign completion reward, a regenerating energy bar and a reward counter with a reset are different systems. Open the activity and read entry conditions, reward conditions and the refresh indicator separately. Do not treat the words “Daily Dungeon” as proof that its reward allowance refills every day.','このチェックリストは利用可能な活動を整理するもので、独立したゲームモードではありません。ストーリーの一度限りの報酬、時間で回復するエネルギー、更新される報酬回数は別々の仕組みです。活動画面で参加条件、報酬条件、更新表示を個別に確認します。「Daily Dungeon」という名称だけから毎日報酬枠が補充されると判断しないでください。','Esta lista organiza actividades disponibles; no es un modo de juego. Una recompensa única, energía que se regenera y un contador que se reinicia son sistemas distintos. Lee condiciones de entrada, recompensa y actualización por separado. El nombre Daily Dungeon no demuestra que sus recompensas se repongan cada día.','Diese Liste ordnet verfügbare Aktivitäten; sie ist kein eigener Spielmodus. Einmalige Kampagnenbelohnungen, regenerierende Energie und zurückgesetzte Belohnungszähler sind verschiedene Systeme. Lies Zugang, Belohnungsbedingungen und Aktualisierungsanzeige getrennt. Der Name Daily Dungeon beweist keinen täglichen Belohnungsreset.')),
 ('duty-missions',row('Duty missions after level 45','45到達後のDuty任務','Misiones Duty al nivel 45','Duty-Missionen nach Stufe 45'),row('Open Journal → Duty after reaching 45. Inspect the available mission, its destination, required objective and reward choices before accepting. Group nearby objectives to reduce travel and use a reward needed for your current progression. The October 5 launch update included a fix for Duty access after reaching 45; the old workaround to avoid opening the tab before leveling is obsolete. If the panel remains unavailable, record the client error and contact support.','45到達後にJournal → Dutyを開きます。受注前に任務、目的地、目標、報酬の選択肢を確認してください。近くの目的をまとめて移動を減らし、現在の成長に必要な報酬を選びます。10月5日のアップデートには45到達後のアクセス修正が含まれるため、レベル上げ前にタブを開かないという古い回避策は不要です。まだ利用できない場合はエラーを記録してサポートに相談します。','Abre Journal → Duty al alcanzar 45. Antes de aceptar, revisa destino, objetivo y recompensas. Agrupa objetivos cercanos y elige una recompensa útil para tu progreso. La actualización del 5 de octubre incluyó una corrección de acceso: el consejo antiguo de evitar la pestaña antes de subir ya no procede. Si sigue bloqueada, registra el error y contacta con soporte.','Öffne Journal → Duty auf Stufe 45. Prüfe Zielort, Aufgabe und Belohnungswahl vor der Annahme. Bündle nahe Ziele und wähle nützliche Fortschrittsressourcen. Das Update vom 5. Oktober enthielt eine Zugangskorrektur; der alte Rat, den Reiter vor dem Leveln zu meiden, ist überholt. Halte bei weiterhin gesperrtem Zugang den Fehler für den Support fest.')),
 ('energy-and-rewards',row('Entry, energy and reward claims','入場・エネルギー・報酬受領','Entrada, energía y recompensas','Zugang, Energie und Belohnungen'),row('For Expeditions and other limited activities, choose difficulty before checking requirements. Read the energy or ticket charge and the reward chest separately: completing a run and claiming its reward can be different steps. Before spending Odyle Energy, check the reward you want and whether your remaining supply supports another useful claim. A locked reward counter is not automatically an equipment problem. Inspect the displayed reason before repeating the run.','遠征など回数制限のある活動では、難易度を選んでから条件を確認します。エネルギーやチケットの消費と報酬箱は別に読みます。クリアと報酬受領が別操作の場合があるためです。Odyle Energyを使う前に欲しい報酬と残量を確認し、次の有用な受領にも使えるか判断します。報酬枠のロックを装備不足と決めつけず、再入場する前に表示理由を確認してください。','En Expeditions y actividades limitadas, elige dificultad antes de comprobar requisitos. Lee energía o tickets y el cofre por separado: completar y reclamar pueden ser pasos diferentes. Antes de gastar Odyle Energy, comprueba la recompensa deseada y las reservas para otra reclamación útil. Un contador bloqueado no indica necesariamente un problema de equipo; lee el motivo antes de repetir.','Wähle bei Expeditions und begrenzten Aktivitäten zuerst die Schwierigkeit. Prüfe Energie oder Tickets getrennt von der Belohnungstruhe: Abschluss und Abholen können verschiedene Schritte sein. Kontrolliere vor Odyle-Energy-Verbrauch gewünschte Belohnung und Restvorrat. Ein gesperrter Belohnungszähler ist nicht automatisch ein Ausrüstungsproblem; lies den Grund vor einer Wiederholung.')),
 ('before-a-reset',row('Review before the displayed reset','表示された更新前の確認','Revisión antes del reinicio indicado','Vor dem angezeigten Reset prüfen'),row('At your weekly review, inspect each unlocked activity’s remaining rewards and its actual next reset. Finish useful available rewards before their displayed deadline, rather than following a universal weekday. Check whether the allowance belongs to the current character, server or account before switching characters. Shop limits and recipe limits must be read on the actual offer; a calendar week alone does not establish their refresh rule. This page does not impose an automatic reset or a fixed regional timetable.','週ごとの見直しでは、解放済み活動の残り報酬と実際の更新時刻を確認します。一律の曜日表ではなく、表示期限までに役立つ報酬を受け取ってください。キャラクターを替える前に、枠がキャラクター、サーバー、アカウントのどれに属するかを確認します。店やレシピの制限は実際の販売・製作画面で読みます。暦の一週間だけでは更新条件はわかりません。このページでは自動リセットや固定時刻表を設定しません。','En la revisión semanal, comprueba recompensas restantes y próximo reinicio real de cada actividad desbloqueada. Completa lo útil antes del plazo mostrado, sin asumir un día universal. Antes de cambiar de personaje, revisa si el cupo es por personaje, servidor o cuenta. Lee los límites de tiendas y recetas en la oferta real. Esta página no aplica reinicios automáticos ni un horario fijo.','Prüfe bei der Wochenübersicht verbleibende Belohnungen und den tatsächlichen nächsten Reset jeder freigeschalteten Aktivität. Nutze angezeigte Fristen statt eines pauschalen Wochentags. Prüfe vor Charakterwechsel, ob das Kontingent für Charakter, Server oder Konto gilt. Lies Kauf- und Rezeptlimits am tatsächlichen Angebot. Diese Seite setzt nichts automatisch zurück und gibt keinen festen Zeitplan vor.')),
 ('one-time-and-events',row('One-time rewards and events','一度限りの報酬とイベント','Recompensas únicas y eventos','Einmalige Belohnungen und Events'),row('Keep sealed dungeons, stronghold completion and campaign rewards on a separate exploration list. Their first-clear benefits should not be copied into a repeating routine. Check mail for launch gifts and claim a coupon through its own menu; Twitch Drops require the linked playing account and Twitch inventory claim. Each promotion has its own deadline. A daily task reset does not extend an event or an expiring mail reward.','封印ダンジョン、拠点の初回完了、ストーリー報酬は別の探索リストで管理します。初回の恩恵を繰り返し活動へ入れないでください。公開記念の贈り物はメールを確認し、クーポンは専用メニューで受け取ります。Twitch Dropsはプレイ用アカウントの連携とTwitchインベントリでの受領が必要です。各イベントには独自の期限があり、毎日の更新でイベントやメールの期限は延長されません。','Separa mazmorras selladas, primeras fortalezas y campaña en una lista de exploración. No conviertas sus primeras recompensas en tareas repetibles. Revisa correo para regalos, el menú de cupones y el inventario de Twitch para Drops con la cuenta enlazada. Cada promoción tiene su propio plazo; un reinicio diario no amplía eventos ni correo que caduca.','Führe versiegelte Dungeons, erste Festungsabschlüsse und Kampagnenbelohnungen getrennt als Erkundung. Erste Abschlussboni gehören nicht in eine Wiederholungsroutine. Prüfe Post für Geschenke, das Couponmenü und Twitch-Inventar für Drops mit dem verknüpften Spielkonto. Jede Aktion hat eine eigene Frist; tägliche Resets verlängern weder Events noch ablaufende Post.')),
 ('short-session',row('A useful short session','短い時間で進める','Una sesión corta útil','Eine sinnvolle kurze Sitzung'),row('Start by inspecting Duty, then choose one activity that supplies the resource for your next upgrade. Read its allowance before entry, complete the objective and confirm the reward was claimed. If the next step needs a quest unlock or a one-time exploration reward, do that instead of an unrelated repeated run. Before logging out, note remaining counters, the next displayed deadline and the exact material still missing. Read this checklist alongside your equipment goal, not as a requirement to complete everything.','最初にDutyを確認し、次の強化に必要な素材を得られる活動を一つ選びます。参加前に残り枠を読み、目標を完了して報酬受領を確認します。次に必要なのがクエスト解放や初回探索報酬なら、関係のない周回よりそちらを進めてください。終了前に残り枠、次の表示期限、足りない素材名を記録します。すべてを必ず終えるための義務ではなく、装備の目標に合わせて使う一覧です。','Empieza por Duty y elige una actividad que dé recursos para la próxima mejora. Lee el cupo antes de entrar, completa el objetivo y confirma la recompensa. Si necesitas un desbloqueo o exploración única, hazlo en vez de repetir algo ajeno. Al salir, anota contadores, próximo plazo y material faltante. Usa la lista según tu objetivo, sin convertirla en obligación de terminar todo.','Prüfe zuerst Duty und wähle eine Aktivität mit Material für die nächste Verbesserung. Lies das Kontingent vor dem Eintritt und bestätige danach die erhaltene Belohnung. Erledige erforderliche Questfreischaltung oder einmalige Erkundung statt einer unpassenden Wiederholung. Notiere vor dem Ausloggen Restzähler, nächste Frist und fehlendes Material. Nutze die Liste passend zum Ausrüstungsziel, nicht als Pflichtprogramm.')),
 ]},
'crafting':{
 'labels':row('Crafting','製作','Fabricación','Herstellung'),
 'quick':row('Choose a recipe for an item you will use, inspect its profession and material requirements, then prepare one batch. Gathering, equipment extraction and Substance Morph supply different inputs; verify the exact item and Bound status before crafting.','使う予定のアイテムのレシピを選び、専門分野と素材条件を確認して一回分を用意します。採集、装備抽出、Substance Morphは異なる入力を扱います。製作前に正確なアイテム名とBound条件を照合してください。','Elige una receta útil, comprueba profesión y materiales y prepara un lote. Recolección, extracción de equipo y Substance Morph aportan entradas distintas; verifica el objeto exacto y su estado Bound antes de fabricar.','Wähle ein nützliches Rezept, prüfe Beruf und Materialien und bereite eine Charge vor. Sammeln, Ausrüstungsextraktion und Substance Morph liefern unterschiedliche Eingänge; prüfe genauen Gegenstand und Bound-Status.'),
 'next':'gathering','related':['gear-progression','monetization','daily-weekly-checklist'],
 'sections':[
 ('start-with-a-recipe',row('Choose the result before the profession','専門分野より先に完成品を選ぶ','Elige el resultado antes de la profesión','Ergebnis vor dem Beruf wählen'),row('Open Crafting and find the item you intend to make. Read the profession, required crafting level, output and material list before spending progression resources. Start with a recipe that contributes to an equipment upgrade or a consumable you actually use. Do not choose a profession solely because someone calls it the best: its useful recipes, ingredient demand and your available materials determine whether it serves your character.','Craftingを開き、作りたいアイテムを探します。成長資源を使う前に専門分野、必要製作レベル、完成品、素材一覧を読んでください。装備更新や実際に使う消耗品につながるレシピから始めます。他人の最強という評価だけで専門分野を決めません。有用なレシピ、素材の需要、現在の所持品が自分のキャラクターに役立つかを判断する基準です。','Abre Crafting y busca el objeto que quieres crear. Lee profesión, nivel, resultado y materiales antes de gastar recursos. Empieza con una receta para equipo o consumibles que usarás. La utilidad depende de recetas, ingredientes y reservas, no de que alguien llame a una profesión la mejor.','Öffne Crafting und suche den gewünschten Gegenstand. Lies Beruf, erforderliche Herstellungsstufe, Ergebnis und Materialliste vor dem Ressourceneinsatz. Beginne mit Ausrüstung oder Verbrauchsgegenständen, die du nutzt. Nützliche Rezepte, Zutatenbedarf und Vorräte entscheiden über den Beruf, nicht eine pauschale Bestbewertung.')),
 ('different-material-systems',row('Gathering, extraction and morphing','採集・抽出・変換を区別する','Recolección, extracción y transformación','Sammeln, Extraktion und Umwandlung'),row('Essence Extraction is gathering from resource nodes. Item Extraction dismantles equipment; it is not the same proficiency bar. Substance Morph converts listed inputs through a recipe, including some equipment progression recipes. Keep the source item until you have checked its uses and the recipe output. A gathering promotion quest item is not interchangeable with a similarly named ordinary crafting material. Match the full name, quality and binding state.','Essence Extractionは採集ポイントから素材を集める操作です。Item Extractionは装備を分解する操作で、同じ熟練度ではありません。Substance Morphは指定入力をレシピで変換し、一部の装備成長にも使います。用途と完成品を確認するまで入力アイテムは保管します。採集昇級クエストの品を似た名前の通常素材で代用できるとは限らないため、名称、品質、バインド状態を一致させます。','Essence Extraction recoge nodos; Item Extraction desmantela equipo y usa un sistema distinto. Substance Morph convierte entradas mediante recetas, incluidas algunas mejoras de equipo. Conserva el objeto hasta comprobar usos y resultado. Un objeto de promoción de recolección no equivale a un material común de nombre parecido: compara nombre completo, calidad y vinculación.','Essence Extraction sammelt an Ressourcenknoten. Item Extraction zerlegt Ausrüstung und ist ein anderes System. Substance Morph wandelt angegebene Eingänge per Rezept um, auch für manche Ausrüstungsfortschritte. Bewahre Eingänge bis zur Prüfung auf. Ein Sammelaufstiegs-Questgegenstand ist kein Ersatz für ähnlich benanntes gewöhnliches Material; gleiche vollständigen Namen, Qualität und Bindung ab.')),
 ('prepare-a-batch',row('Prepare one batch of materials','一回分の素材を準備する','Prepara un lote de materiales','Material für eine Charge vorbereiten'),row('Record the recipe’s required quantity of each material and the quantity already available. Subtract your usable stock before planning a gathering route or purchase. Check whether the recipe accepts the item you own, including Bound variants. Read crafting quantity carefully: changing the batch size can multiply both ingredients and currency. Reserve equipment or materials used by another quest before confirming consumption.','レシピの各素材必要数と使用できる所持数を記録します。採集や購入を計画する前に所持分を差し引いてください。Bound違いを含め、所持品を入力に使えるか確認します。製作数を増やすと素材と通貨の総額も増えるため、回数表示を読みます。他のクエストで使う装備や素材は消費確認前に確保しておきます。','Anota la cantidad requerida y disponible de cada ingrediente. Resta existencias utilizables antes de recolectar o comprar. Comprueba variantes Bound y el tamaño del lote: varias unidades multiplican materiales y moneda. Reserva objetos que necesitas en otra misión antes de confirmar el consumo.','Notiere erforderliche und verfügbare Menge jeder Zutat. Ziehe nutzbare Vorräte vor Sammelroute oder Kauf ab. Prüfe Bound-Varianten und Chargengröße: Mehrere Einheiten können Zutaten und Währung vervielfachen. Reserviere Material oder Ausrüstung für andere Quests vor der Verbrauchsbestätigung.')),
 ('gather-or-buy',row('Gather or buy the missing inputs','不足分を採集するか購入するか','Recolecta o compra lo que falta','Fehlende Eingänge sammeln oder kaufen'),row('For a gatherable input, inspect the node’s requirement and your Essence Extraction stage. A short nearby route is useful only if it yields the recipe’s actual material. For a purchase, compare the total quantity price rather than one listing’s unit price. Market access has membership conditions, so include access cost and availability in that comparison. The material budget tool can record your own quantities and prices without assuming a fixed market value.','採集できる素材はノードの条件とEssence Extraction段階を確認します。短い近場の経路でも、実際にレシピで使う素材が得られなければ目的に合いません。購入では単価だけでなく必要数の合計を比較してください。市場にはメンバーシップ条件があるため、利用費用と利用可能性も含めます。素材予算ツールには自分の数量と価格を入力でき、固定相場を前提にしません。','Para recolectar, comprueba nodo y nivel de Essence Extraction. Una ruta cercana solo sirve si da el ingrediente correcto. Para comprar, compara el precio total de la cantidad necesaria. El mercado requiere membresía, así que considera acceso y coste. La herramienta de presupuesto permite guardar tus cantidades y precios sin suponer un valor fijo.','Prüfe für Sammelmaterial Knotenanforderung und Essence-Extraction-Stufe. Eine nahe Route hilft nur mit der tatsächlich benötigten Zutat. Vergleiche beim Kauf den Gesamtpreis der Menge. Der Markt hat Mitgliedschaftsbedingungen; berücksichtige Zugang und Kosten. Der Materialplaner nutzt deine Mengen und Preise statt eines festen Marktwerts.')),
 ('first-craft',row('Complete and inspect the first craft','最初の製作結果を確認する','Completa y revisa la primera fabricación','Erste Herstellung abschließen und prüfen'),row('Select the intended recipe and start with one batch. Recheck output, ingredients, currency and the displayed conditions before confirming. Afterwards, inspect the inventory result and the profession progress separately. If the item cannot be used, compare class, level and binding conditions before crafting another copy. Do not assume an exceptional outcome or a guaranteed success rate when the recipe does not show one. Keep the actual result as your reference for the next batch.','対象レシピで一回分から始めます。確定前に完成品、素材、通貨、表示条件を再確認してください。完了後は所持品の結果と専門分野の進行を別々に確認します。使えない場合は、もう一つ作る前に職業、レベル、バインド条件を照合します。レシピに表示されていない特別な結果や確定成功率を仮定しません。実際に得た結果を次の製作の基準にします。','Selecciona la receta y empieza con un lote. Revisa resultado, ingredientes, moneda y condiciones antes de confirmar. Después comprueba objeto y progreso de profesión por separado. Si no puedes usarlo, revisa clase, nivel y vinculación antes de crear otro. No supongas resultados especiales ni éxito garantizado que la receta no indique.','Wähle das Rezept und beginne mit einer Charge. Kontrolliere Ergebnis, Zutaten, Währung und Bedingungen vor der Bestätigung. Prüfe danach Gegenstand und Berufsfortschritt getrennt. Untersuche bei unbenutzbarem Ergebnis Klasse, Stufe und Bindung vor einer weiteren Kopie. Unterstelle keine besonderen Ergebnisse oder garantierten Erfolg, den das Rezept nicht anzeigt.')),
 ('crafting-blockers',row('Fix a blocked recipe','製作できない原因を解決する','Resuelve una receta bloqueada','Ein gesperrtes Rezept lösen'),row('If the recipe is locked, read its profession or unlock requirement. If materials appear missing despite your inventory, compare the exact name and eligible variant, then check the selected batch quantity. For an equipment input, check whether it remains equipped in a preset. If a limit is exhausted, read that recipe’s refresh information rather than treating it as a gathering problem. Stop when the next batch does not advance your chosen item or profession goal; save materials for the next useful recipe.','ロックされたレシピは専門分野や解放条件を確認します。所持しているのに素材不足と表示される場合は正確な名称、使える種類、選択製作数を照合してください。装備入力ではプリセットに装備されたままかも確認します。制限回数を使い切った場合は、そのレシピの更新情報を読み、採集不足と混同しません。次の製作が目的の装備や専門分野を進めないなら止め、次に役立つレシピのために素材を保管します。','Si está bloqueada, lee profesión o desbloqueo. Si faltan materiales que tienes, compara nombre, variante válida y tamaño del lote. Para equipo de entrada, revisa conjuntos donde siga equipado. Si agotaste un límite, lee la actualización de esa receta. Detente cuando otro lote no contribuya a tu objeto o profesión y guarda materiales para algo útil.','Lies bei gesperrtem Rezept Berufs- oder Freischaltbedingungen. Prüfe bei scheinbar fehlendem vorhandenem Material Namen, gültige Variante und Chargengröße. Kontrolliere bei Ausrüstungseingängen ausgerüstete Vorlagen. Lies bei verbrauchtem Limit die Rezeptaktualisierung. Beende Chargen ohne Nutzen für Gegenstand oder Beruf und spare Material für das nächste sinnvolle Rezept.')),
 ]},
}
flow=row('Check, prepare, confirm','条件を確認し、準備して確定する','Comprueba, prepara y confirma','Prüfen, vorbereiten, bestätigen')
steps=[row('Read the requirement','条件を読む','Lee el requisito','Voraussetzung lesen'),row('Prepare one operation','一回分を準備する','Prepara una operación','Einen Vorgang vorbereiten'),row('Inspect the result','結果を確認する','Revisa el resultado','Ergebnis prüfen')]
details=[row('Read the selected menu, item and current conditions.','選択画面、アイテム、現在の条件を確認します。','Lee el menú, objeto y condiciones actuales.','Lies Menü, Gegenstand und aktuelle Bedingungen.'),row('Check the inputs, bindings or costs before confirming.','確定前に入力、キー、費用を確認します。','Revisa entradas, teclas o costes antes de confirmar.','Prüfe Eingänge, Tasten oder Kosten vor dem Bestätigen.'),row('Test the outcome before repeating or investing more.','再実行や追加投資の前に結果を試します。','Prueba el resultado antes de repetir o invertir más.','Prüfe das Ergebnis vor Wiederholung oder weiterer Investition.')]
related_label=row('Continue with','次に読む','Continúa con','Weiterlesen')
for slug,p in PAGES.items():
 for loc in LOCALES:
  body=[]
  for i,(anchor,title,text) in enumerate(p['sections']):
   body.append(f'<h2 id="{anchor}">{title[loc]}</h2>\n\n{text[loc]}')
   if i==2:body.append('<GuideVisual id="workflow" />')
  body.append(related_label[loc]+': '+', '.join(f'[{PAGES[t]["labels"][loc] if t in PAGES else t}](/'+t+')' for t in p['related'])+'.')
  body.append(f'<GuideNext slug="{p["next"]}" />')
  meta={'title':('AION2' if loc=='ja' else 'AION 2')+' '+p['labels'][loc],'description':p['quick'][loc],'summary':p['sections'][0][2][loc],'quickAnswer':p['quick'][loc],'toc':[{'id':a,'title':t[loc]} for a,t,b in p['sections']],'visuals':{'workflow':{'title':flow[loc],'caption':details[0][loc]+' '+details[2][loc],'steps':[{'label':steps[i][loc],'description':details[i][loc]} for i in range(3)]}},'inlineNext':[p['next']]}
  (ROOT/'src/content'/loc/f'{slug}.mdx').write_text('\n\n'.join(body)+'\n',encoding='utf-8');save(ROOT/'src/content'/loc/f'{slug}.json',meta)
  mpath=ROOT/'src/messages'/f'{loc}.json';m=json.loads(mpath.read_text(encoding='utf-8'));m['topics'][slug]=p['labels'][loc];save(mpath,m)
 sources=[{'id':'steam-launch','title':'Launch Into AION 2 Now!','url':'https://steamcommunity.com/games/3393110/announcements/detail/712288224875119583','kind':'official','region':'Global','publishedAt':'2026-10-05','version':'Steam App 3393110 official launch notice captured 2026-10-06; establishes the supported public service, not every system value.'}]
 vid='Ei17ATvSLGM' if slug=='settings' else 'J8WVY3FxPQM'
 src=json.loads((ROOT/'research/youtube/2026-10-06-beginner-guides/sources'/vid/'source.json').read_text(encoding='utf-8'))
 sources.append({'id':'tutorial-'+vid,'title':src['title'],'url':src['url'],'kind':'player','region':'Global','publishedAt':src['upload_date'],'version':'Global audience stated in original description/introduction; subtitle and frame review retained in steam-beginner-refresh. Numeric thresholds, reset predictions and universal recommendations excluded.'})
 if slug=='daily-weekly-checklist':sources.append({'id':'steam-duty-fix','title':'Scheduled Maintenance Sun Oct 4 / Mon Oct 5','url':'https://steamcommunity.com/games/3393110/announcements/detail/689769594581155933','kind':'official','region':'Global','publishedAt':'2026-10-04','version':'October5 launch update: Journal-Duty level45 access fix; no quota or reset weekday asserted.'})
 save(ROOT/'src/content/article-data'/f'{slug}.json',{'slug':slug,'keyword':'aion 2 '+slug.replace('-',' '),'checkedAt':'2026-10-06','revision':'2026-10-06.steam-beginner-1','regions':['Global'],'related':p['related'],'sources':sources})
for filename in ['content-topics.json','keywords.json']:
 path=ROOT/filename;data=json.loads(path.read_text(encoding='utf-8'))
 for slug in PAGES:
  category='installation and controls' if slug=='settings' else 'guide'
  group=next(g for g in data['categories'] if g['category']==category)
  keyword='aion 2 '+slug.replace('-',' ')
  if keyword not in group['keywords']:group['keywords'].append(keyword)
 save(path,data)
path=ROOT/'src/lib/articles.ts';t=path.read_text(encoding='utf-8')
imports=[]
for slug in PAGES:
 name=slug.replace('-','_');imports.append(f"import data_{name} from '@/content/article-data/{slug}.json';")
 for loc in LOCALES:imports.append(f"import meta_{loc}_{name} from '@/content/{loc}/{slug}.json';")
t='\n'.join(imports)+'\n'+t
t=t.replace('const sharedData = {','const sharedData = {\n'+ '\n'.join(f"  '{s}': data_{s.replace('-','_')}," for s in PAGES))
for loc in LOCALES:t=t.replace(f'  {loc}: {{',f'  {loc}: {{\n'+'\n'.join(f"    '{s}': {{metadata: meta_{loc}_{s.replace('-','_')}, load: () => import('@/content/{loc}/{s}.mdx')}}," for s in PAGES))
path.write_text(t,encoding='utf-8')
path=ROOT/'src/lib/reading-paths.ts';t=path.read_text(encoding='utf-8').replace("  guide: ['leveling', 'builds'], gathering: ['map', 'monetization'], leveling: ['map', 'builds'],","  guide: ['settings', 'leveling'], gathering: ['crafting', 'map'], leveling: ['gear-progression', 'builds'],")
t=t.replace('= {','= {\n'+ '\n'.join(f"  '{s}': ['{p['next']}', '{p['related'][0]}']," for s,p in PAGES.items()),1);path.write_text(t,encoding='utf-8')
print('Created four localized article families, metadata, evidence and published registrations.')
