import type {Locale} from './routing';

type VideoMessages = {title: string; intro: string; all: string; start: string; gear: string; watch: string; browse: string; english: string; recommended: string; filter: string; count: string; homeTitle: string};
export const videoMessages: Record<Locale, VideoMessages> = {
  en: {title: 'Beginner video guides', intro: 'Choose a video for your current step: setting up your character or progressing after level 45. Videos open on YouTube.', all: 'All videos', start: 'Getting started', gear: 'Level 45 & equipment', watch: 'Watch on YouTube', browse: 'Browse video guides', english: 'English audio', recommended: 'Watch the next step', filter: 'Filter videos by stage', count: 'videos', homeTitle: 'Learn your next step in action'},
  ja: {title: '初心者向け動画ガイド', intro: '最初の設定やレベル45以降の成長など、今の段階に合う動画を選べます。動画はYouTubeで開きます。', all: 'すべての動画', start: '始める前に', gear: 'レベル45と装備', watch: 'YouTubeで見る', browse: '動画ガイドを見る', english: '英語音声', recommended: '次の操作を動画で確認', filter: '段階で動画を絞り込む', count: '件の動画', homeTitle: '次の操作を映像で確認'},
  es: {title: 'Vídeos para principiantes', intro: 'Elige un vídeo para tu etapa: preparar el personaje o avanzar después del nivel 45. Los vídeos se abren en YouTube.', all: 'Todos los vídeos', start: 'Primeros pasos', gear: 'Nivel 45 y equipo', watch: 'Ver en YouTube', browse: 'Explorar las guías en vídeo', english: 'Audio en inglés', recommended: 'Mira el siguiente paso', filter: 'Filtrar vídeos por etapa', count: 'vídeos', homeTitle: 'Mira cómo dar el siguiente paso'},
  de: {title: 'Videoguides für Einsteiger', intro: 'Wähle ein Video für deinen nächsten Schritt: Charaktereinrichtung oder Fortschritt nach Stufe 45. Die Videos öffnen sich auf YouTube.', all: 'Alle Videos', start: 'Erste Schritte', gear: 'Stufe 45 und Ausrüstung', watch: 'Auf YouTube ansehen', browse: 'Videoguides ansehen', english: 'Englische Vertonung', recommended: 'Den nächsten Schritt ansehen', filter: 'Videos nach Phase filtern', count: 'Videos', homeTitle: 'Den nächsten Schritt in Aktion sehen'},
};
